### ISSUE TITLE
Install guide?

### ISSUE THREAD

**Issue by nnotfilc** [fortheusers/hb-appstore#4]
Are you able to install this like Hombrew Menu? If no what is the proper way to install this? Or can you point me in the right direction. And what firmware is this compatible with? Thanks in advance.

**Comment by vgmoose** [comment]
Yes, it's a .nro intended to be used with hbmenu (which is 3.0.0 only for now). Added [instructions to the readme](https://github.com/vgmoose/appstorenx#usage).

If you don't have a switch on 3.0.0, it should also run in the [RyujiNX emulator](https://zoltx23.github.io/ryujinx-emu/).

**Comment by nnotfilc** [comment]
Ok thank you. Have you heard of anyway to downgrade firmware on switch. Or update firmware with sd card?

**Comment by vgmoose** [comment]
**For downgrading**

Unfortunately there are [anti-downgrade](http://switchbrew.org/index.php?title=Fuse_registers#Anti-downgrade) measures built into the Switch. On most firmware updates, physical fuses are burnt and if too few fuses are burnt at boot time for a given firmware the console will refuse to boot.

Due to Nintendo releasing security updates to the console, the newer the firmware on the console, the longer someone will have to wait to be able to use Homebrew apps. As a result of this, an eventual goal of homebrew/exploits is to gain lower-level persistence to be able to get around these limitations. (Such as being able to use 5.0.0 without actually upgrading from 3.0.0).

A good place to follow these exploit/homebrew developments on the [Reswitched Discord server](https://discord.gg/DThbZ7z). 

**For upgrading**

If a console is on **1.0.0**, it shouldn't be updated as there are lower-level vulnerabilities present on it (but not yet a method of running HBL).

If a console is on **2.0.0**, some revisions of the game Pokken contain firmware 3.0.0, this can be used to update a 2.x system to 3.0.0.

If a console is on **≤ 4.1.0**, it is vulnerable but a public exploit chain hasn't been released yet. It should be kept offline or have updates blocked.

If the console is on **5.0.0** or higher (5.0 was released a few days ago) then isn't any word on what vulnerabilities are present, but some new security measures were added.

**Comment by nnotfilc** [comment]
Thanks for all the info i really appreciate it. Nintendo is try too hard to stop whats eventually going to happen anyways. I Wonder what firmware is preinstalled on consoles in stores right now.
