### ISSUE TITLE
failed to boot atmosphere after installing it from hb-appstore

### ISSUE THREAD

**Issue by abluejay-piyo** [fortheusers/hb-appstore#57]
**Package:**
atmosphere 0.10.5

**Describe the problem**
I have 0.10.4 installed in SD card (no emuMMC). I install 0.10.5 via appstore. failed to reboot.

**Platform:**
Switch 9.1

**Comment by vgmoose** [comment]
Today I updated AMS via appstore and was reminded of this issue. On my console it was successful, but on a friend's it broke due to their kosmos/hekate config not being properly updated. (as it isn't part of the AMS package)

Where did you get your original atmosphere install from? It seems if using Kosmos it's better to use the kosmos updater. Probably we can avoid this situation in the future by detecting conflicting packages, or being smarter about updating bundled tools all at once.

I should also note, that updating Hekate through app store works as well, but it may break the first reboot for RCM users. The "Reboot to Payload" appears to go to the older Hekate, which may not support the console after a ninty system FW update

**Comment by vgmoose** [comment]
Atmosphere has been removed, both due to SciresM's direct request, and the fact that it has some special concerns during the update process.

It can still be done on-console using [aio-switch-updater](https://github.com/HamletDuFromage/aio-switch-updater), which as of time of writing is excluded from the 4tu switch repo due to allowing the user to install and update sigpatches.
