### ISSUE TITLE
Hb App store Wii U | Cant enter app

### ISSUE THREAD

**Issue by CezarFSociety** [fortheusers/hb-appstore#62]
downlaoded it and put it in to the right folders.
wiiu - apps - appstore
i put it at the root of the sd card.
when i enter homebrew it shows like its there, but when i enter it, gives me 2 sec of black screen and then just goes back to the hb menu

**Comment by vgmoose** [comment]
What version of HBL are you using? Can you try with this one? https://apps.fortheusers.org/wiiu/homebrew_launcher

I suspect this is an issue with loading .rpx files

**Comment by louvenarde** [comment]
Fixed it for me!

**Comment by M1CR0H4CK3R** [comment]
I'm trying to load HB Appstore on my US Wii U with an Onn 32GB microSD/SD adapter combo, and getting an infinite black screen. Is the 'versions.json' file bundled with tiramisu required for homebrew to run? That's the only missing thing I can think of. I have everything working except this homebrew, which means that I'll need to use my tablet as an MTP device again to manually install homebrew, which I would prefer to avoid doing. I do indeed have sigpatches and Pretendo working as intended as well. It's just this homebrew.

**Comment by vgmoose** [comment]
Could you test it with [this RPX](https://github.com/fortheusers/hb-appstore/suites/8429699834/artifacts/373293765)? (Latest [GH Actions build](https://github.com/fortheusers/hb-appstore/actions)).

All that should be needed to run is the RPX. You could see if "recovery mode" works (Spamming L+R while the app is launching). A black screen to me usually implies an issue with either the HBL version, or the RPX itself.

**Comment by M1CR0H4CK3R** [comment]
> Could you test it with [this RPX](https://github.com/fortheusers/hb-appstore/suites/8429699834/artifacts/373293765)? (Latest [GH Actions build](https://github.com/fortheusers/hb-appstore/actions)).
> 
> All that should be needed to run is the RPX. You could see if "recovery mode" works (Spamming L+R while the app is launching). A black screen to me usually implies an issue with either the HBL version, or the RPX itself.

It turns out that the app doesn't launch correctly if I'm using the TV that the Wii U is hooked up to in another mode. I use my PC in HDMI 1, and my Wii U in HDMI 2, and if the TV is set to HDMI 1 when launching the app, it results in a black screen. My TV is a VIZIO E321VL 32.1-inch HDTV. You might want to look into that issue. When I launch with my TV in HDMI 2 it works perfectly.

**Comment by Masamune3210** [comment]
The WiiU can operate completely headless perfectly fine, maybe see if the issue happens if you unplug the HDMI from the WiiU completely? Just throwing ideas out

**Comment by vgmoose** [comment]
Also, could you try with an SDL app? Like one of these:
- https://apps.fortheusers.org/wiiu/Simple_SDL_Snake
- https://apps.fortheusers.org/wiiu/SuDokuL

Maybe they have the same behavior

**Comment by M1CR0H4CK3R** [comment]
> Also, could you try with an SDL app? Like one of these:
> 
> * https://apps.fortheusers.org/wiiu/Simple_SDL_Snake
> * https://apps.fortheusers.org/wiiu/SuDokuL
> 
> Maybe they have the same behavior

I stopped having the issue for a while, but now it's happening again, but it seems to happen whether the TV is set to HDMI 2 or not, so the last time I think I just got lucky. Turns out also that this isn't the only app that has this issue, as WUP Installer GX2 also refuses to boot, only resulting in an infinite black screen. There's no error message, as the console simply freezes and I have to hold down the power button to turn off the console. FTPiiU does work, but WiiU-Shell does not. I have yet to try other apps. It may be my HDMI cable, as I didn't have a Nintendo-original one, and used one that I thought was having shorting out issues at one point, so I stopped using it to be extra safe. The cable in question seems to work just fine with my Wii U, however, as all features work as intended, except these homebrew, on occasion.

**Comment by M1CR0H4CK3R** [comment]
I have also just replaced the .rpx again, but since the issue is happening with multiple homebrews, it isn't likely bad file transfers. The microSD/SD combo was bought from a brick and mortar Walmart store, so it absolutely cannot be fake, and was brand new. While it could be faulty out of the box, I doubt it, but I have no way to run h2testw because my PC has no SD card slot, and Windows 10 and newer's memory card reader driver is broken, and has been since its inception, so I cannot even use one anyway,

**Comment by M1CR0H4CK3R** [comment]
> Could you test it with [this RPX](https://github.com/fortheusers/hb-appstore/suites/8429699834/artifacts/373293765)? (Latest [GH Actions build](https://github.com/fortheusers/hb-appstore/actions)).

Just tried this. Same result.

**Comment by M1CR0H4CK3R** [comment]
I am also using Tiramisu with this app, in case it's important.

**Comment by M1CR0H4CK3R** [comment]
I am also using the ELF version of HBL v1.5, which was included with Tiramisu.

**Comment by M1CR0H4CK3R** [comment]
Okay, so switching to HBL v1.4 seems to have resolved all issues for me.

**Comment by Timbo303** [comment]
> I'm trying to load HB Appstore on my US Wii U with an Onn 32GB microSD/SD adapter combo, and getting an infinite black screen. Is the 'versions.json' file bundled with tiramisu required for homebrew to run? That's the only missing thing I can think of. I have everything working except this homebrew, which means that I'll need to use my tablet as an MTP device again to manually install homebrew, which I would prefer to avoid doing. I do indeed have sigpatches and Pretendo working as intended as well. It's just this homebrew.

I know what the issue is with this I had the same problem. So you need to move the 30_nimble.rpx out of tiramisu folder under environments to the root since app store doesn't support connecting thru pretendo yet. I think he has to add pretendo support yet for this app to work if you have pretendo enabled,
